export interface Specialist {
  id: string;
  name: string;
  emoji: string;
  role: string;
  tagline: string;
  voice: 'alloy' | 'echo' | 'fable' | 'onyx' | 'nova' | 'shimmer';
  cardGradient: string;
  cardGlow: string;
  headerGradient: string;
  headerAccent: string;
  contentBg: string;
  answerColor: string;
  accentColor: string;
  accentBg: string;
  inputBorder: string;
  examples: string[];
  placeholder: string;
  thinkingText: string;
  answerLabel: string;
  answerFont: string;
  hasPhoto: boolean;
  greeting: string;
  voiceGreeting: string;
}

export const SPECIALISTS: Specialist[] = [
  {
    id: 'petya',
    name: 'Отличник Петя',
    emoji: '🧑‍🎓',
    role: 'Репетитор',
    tagline: 'Все предметы · Любой класс',
    voice: 'fable',
    cardGradient: 'linear-gradient(135deg,#1a237e,#1565c0)',
    cardGlow: 'rgba(21,101,192,0.4)',
    headerGradient: 'linear-gradient(135deg,#1a237e 0%,#283593 60%,#1565c0 100%)',
    headerAccent: '#90caf9',
    contentBg: '#fefef4',
    answerColor: '#0d47a1',
    accentColor: '#1a237e',
    accentBg: '#e8eaf6',
    inputBorder: '#c5cae9',
    examples: ['Реши уравнение: 2x + 5 = 17','Правило написания -тся/-ться','Закон Ньютона — примеры'],
    placeholder: 'Напиши задание или сфотографируй его…',
    thinkingText: 'Петя решает задание…',
    answerLabel: 'РЕШЕНИЕ',
    answerFont: '"Caveat", cursive',
    hasPhoto: true,
    greeting: 'Привет! 👋 Я Петя — твой репетитор-отличник.\n\nСоздан командой экосистемы SWAP в Набережных Челнах, чтобы учёба стала проще и интереснее для каждого.\n\nПиши задание или сфотографируй его — решим вместе! 📚',
    voiceGreeting: '',
  },
  {
    id: 'igor',
    name: 'Адвокат Игорь',
    emoji: '⚖️',
    role: 'Юрист',
    tagline: 'Права · Законы · Претензии · Договоры',
    voice: 'onyx',
    cardGradient: 'linear-gradient(135deg,#0d1b2a,#1b2a3b,#243447)',
    cardGlow: 'rgba(139,101,52,0.35)',
    headerGradient: 'linear-gradient(135deg,#0d1b2a 0%,#162032 100%)',
    headerAccent: '#e8c97a',
    contentBg: '#f9f5ec',
    answerColor: '#1a1209',
    accentColor: '#8b6914',
    accentBg: '#f5edcf',
    inputBorder: '#c9a84c',
    examples: ['Составь договор аренды квартиры','Меня незаконно уволили — что делать?','Как взыскать алименты?','Составь претензию в страховую по ОСАГО'],
    placeholder: 'Опишите ситуацию или попросите составить документ…',
    thinkingText: 'Игорь изучает законодательство…',
    answerLabel: 'ОТВЕТ ЮРИСТА',
    answerFont: 'Georgia, serif',
    hasPhoto: true,
    greeting: 'Добрый день.\n\nМеня зовут Игорь — адвокат и юридический консультант экосистемы SWAP, Набережные Челны.\n\nЗнаю всё российское законодательство: гражданское, трудовое, семейное, жилищное, уголовное, административное, налоговое, наследственное, банкротное и другие отрасли.\n\nМогу составить любой юридический документ по нормам РФ — договор, доверенность, расписку, жалобу, претензию, исковое заявление и многое другое.\n\n📸 Новая функция: пришлите мне фото или скан любого документа — паспорта, договора, решения суда, приказа об увольнении, ПТС и других — я сам извлеку все данные и использую их для подготовки нужного документа или консультации. Данные можно также ввести текстом.\n\nНажмите на нужный шаблон ниже или опишите вашу ситуацию.',
    voiceGreeting: '',
  },
  {
    id: 'natasha',
    name: 'Доктор Наташа',
    emoji: '🩺',
    role: 'Врач-терапевт',
    tagline: 'Анализы · Симптомы · Диагнозы · Советы',
    voice: 'shimmer',
    cardGradient: 'linear-gradient(135deg,#00695c,#00897b,#26a69a)',
    cardGlow: 'rgba(0,137,123,0.4)',
    headerGradient: 'linear-gradient(135deg,#00695c 0%,#00897b 100%)',
    headerAccent: '#b2dfdb',
    contentBg: '#f0fffd',
    answerColor: '#004d40',
    accentColor: '#00695c',
    accentBg: '#e0f2f1',
    inputBorder: '#80cbc4',
    examples: ['Что значит повышенный билирубин?','Болит голова каждый день — причины','Расшифруй анализ крови'],
    placeholder: 'Опишите симптомы или задайте вопрос…',
    thinkingText: 'Наташа изучает вопрос…',
    answerLabel: 'КОНСУЛЬТАЦИЯ ВРАЧА',
    answerFont: '"Montserrat", sans-serif',
    hasPhoto: true,
    greeting: 'Здравствуйте. 🩺\n\nЯ Наташа — врач-терапевт экосистемы SWAP, созданной в Набережных Челнах с заботой о здоровье каждого человека.\n\nРасскажите, что вас беспокоит, или пришлите результаты анализов — постараюсь помочь разобраться.',
    voiceGreeting: '',
  },
  {
    id: 'anton',
    name: 'Финансист Антон',
    emoji: '💹',
    role: 'Финансовый консультант',
    tagline: 'Налоги · Ипотека · Инвестиции · Вычеты',
    voice: 'echo',
    cardGradient: 'linear-gradient(135deg,#1b5e20,#2e7d32,#388e3c)',
    cardGlow: 'rgba(46,125,50,0.4)',
    headerGradient: 'linear-gradient(135deg,#1b5e20 0%,#2e7d32 100%)',
    headerAccent: '#a5d6a7',
    contentBg: '#f1fdf2',
    answerColor: '#1b2e1c',
    accentColor: '#2e7d32',
    accentBg: '#e8f5e9',
    inputBorder: '#a5d6a7',
    examples: ['Как получить налоговый вычет за квартиру?','Посчитай ипотеку 4 млн на 20 лет','Куда вложить 100 000 рублей?'],
    placeholder: 'Задайте финансовый вопрос или опишите ситуацию…',
    thinkingText: 'Антон считает и анализирует…',
    answerLabel: 'ФИНАНСОВАЯ КОНСУЛЬТАЦИЯ',
    answerFont: '"Montserrat", sans-serif',
    hasPhoto: true,
    greeting: 'Добрый день! 💹\n\nЯ Антон — финансовый консультант экосистемы SWAP, созданной в Набережных Челнах для грамотного управления личными финансами.\n\nЗадайте вопрос по ипотеке, налоговым вычетам, инвестициям или семейному бюджету — разберём вместе.',
    voiceGreeting: '',
  },
  {
    id: 'marina',
    name: 'HR Марина',
    emoji: '💼',
    role: 'HR-директор',
    tagline: 'Резюме · Собеседования · Карьера · Зарплата',
    voice: 'nova',
    cardGradient: 'linear-gradient(135deg,#4a148c,#6a1b9a,#7b1fa2)',
    cardGlow: 'rgba(106,27,154,0.4)',
    headerGradient: 'linear-gradient(135deg,#4a148c 0%,#6a1b9a 100%)',
    headerAccent: '#e1bee7',
    contentBg: '#fdf5ff',
    answerColor: '#2d0045',
    accentColor: '#6a1b9a',
    accentBg: '#f3e5f5',
    inputBorder: '#ce93d8',
    examples: ['Помоги написать резюме для IT-специалиста','Как отвечать на "расскажите о себе"?','Как просить повышение зарплаты?'],
    placeholder: 'Опишите вашу карьерную ситуацию…',
    thinkingText: 'Марина готовит совет…',
    answerLabel: 'СОВЕТ HR',
    answerFont: '"Montserrat", sans-serif',
    hasPhoto: true,
    greeting: 'Привет! 💼\n\nЯ Марина — HR-директор экосистемы SWAP, созданной в Набережных Челнах для людей, которые хотят расти профессионально.\n\nПомогу составить резюме, подготовиться к собеседованию или принять верное карьерное решение. Расскажи о своей ситуации!',
    voiceGreeting: '',
  },
  {
    id: 'viktor',
    name: 'Шеф-повар Виктор',
    emoji: '👨‍🍳',
    role: 'Шеф-повар',
    tagline: 'Рецепты · Техника · Блюда из холодильника',
    voice: 'fable',
    cardGradient: 'linear-gradient(135deg,#bf360c,#d84315,#e64a19)',
    cardGlow: 'rgba(216,67,21,0.4)',
    headerGradient: 'linear-gradient(135deg,#bf360c 0%,#d84315 100%)',
    headerAccent: '#ffccbc',
    contentBg: '#fff9f5',
    answerColor: '#2d1200',
    accentColor: '#bf360c',
    accentBg: '#fbe9e7',
    inputBorder: '#ffab91',
    examples: ['Что приготовить из курицы и картошки?','Рецепт борща от шефа','Как правильно жарить стейк?'],
    placeholder: 'Что приготовить? Что есть в холодильнике?',
    thinkingText: 'Виктор придумывает рецепт…',
    answerLabel: 'РЕЦЕПТ ОТ ШЕФА',
    answerFont: '"Montserrat", sans-serif',
    hasPhoto: true,
    greeting: 'Добро пожаловать на мою кухню! 👨‍🍳\n\nЯ Виктор — шеф-повар экосистемы SWAP, созданной в Набережных Челнах — городе, где умеют делать всё с душой.\n\nСкажи что есть в холодильнике или пришли фото блюда — вместе придумаем что-нибудь вкусное и сытное!',
    voiceGreeting: '',
  },
  {
    id: 'sasha',
    name: 'Мастер Саша',
    emoji: '🔧',
    role: 'Мастер на все руки',
    tagline: 'Ремонт · Электрика · Сантехника · Техника',
    voice: 'echo',
    cardGradient: 'linear-gradient(135deg,#263238,#37474f,#455a64)',
    cardGlow: 'rgba(55,71,79,0.4)',
    headerGradient: 'linear-gradient(135deg,#263238 0%,#37474f 100%)',
    headerAccent: '#b0bec5',
    contentBg: '#f5f7f9',
    answerColor: '#1a2332',
    accentColor: '#37474f',
    accentBg: '#eceff1',
    inputBorder: '#b0bec5',
    examples: ['Как заменить розетку самому?','Почему плохой напор воды?','Ошибка E2 на стиральной машине'],
    placeholder: 'Опишите поломку или задачу по ремонту…',
    thinkingText: 'Саша думает как починить…',
    answerLabel: 'СОВЕТ МАСТЕРА',
    answerFont: '"Montserrat", sans-serif',
    hasPhoto: true,
    greeting: 'Привет! 🔧\n\nЯ Саша — мастер на все руки из экосистемы SWAP, созданной в Набережных Челнах.\n\nЭлектрика, сантехника, техника, ремонт — всё по делу. Опиши что сломалось или сфотографируй — разберёмся!',
    voiceGreeting: '',
  },
  {
    id: 'alina',
    name: 'Психолог Алина',
    emoji: '🌸',
    role: 'Психолог-консультант',
    tagline: 'Поддержка · Тревога · Отношения · Выгорание',
    voice: 'shimmer',
    cardGradient: 'linear-gradient(135deg,#880e4f,#ad1457,#c2185b)',
    cardGlow: 'rgba(173,20,87,0.4)',
    headerGradient: 'linear-gradient(135deg,#880e4f 0%,#ad1457 100%)',
    headerAccent: '#f8bbd0',
    contentBg: '#fff5f9',
    answerColor: '#3e0022',
    accentColor: '#ad1457',
    accentBg: '#fce4ec',
    inputBorder: '#f48fb1',
    examples: ['Постоянно тревожусь и не могу расслабиться','Конфликт с партнёром — как помириться?','Как справиться с выгоранием?'],
    placeholder: 'Поделитесь, что вас беспокоит…',
    thinkingText: 'Алина обдумывает ответ…',
    answerLabel: 'ОТВЕТ ПСИХОЛОГА',
    answerFont: '"Montserrat", sans-serif',
    hasPhoto: true,
    greeting: 'Здравствуйте. 🌸\n\nЯ Алина — психолог-консультант экосистемы SWAP, созданной в Набережных Челнах с искренней заботой о людях.\n\nЗдесь безопасно, без осуждений и торопливости. Расскажите, что вас беспокоит — я слушаю.',
    voiceGreeting: '',
  },
  {
    id: 'dima',
    name: 'Маркетолог Дима',
    emoji: '🚀',
    role: 'Маркетолог и копирайтер',
    tagline: 'Тексты · Реклама · Бренд · Продвижение',
    voice: 'fable',
    cardGradient: 'linear-gradient(135deg,#e65100,#f57c00,#ff9800)',
    cardGlow: 'rgba(245,124,0,0.4)',
    headerGradient: 'linear-gradient(135deg,#e65100 0%,#f57c00 100%)',
    headerAccent: '#ffe0b2',
    contentBg: '#fffbf5',
    answerColor: '#2d1500',
    accentColor: '#e65100',
    accentBg: '#fff3e0',
    inputBorder: '#ffcc80',
    examples: ['Придумай название для кофейни','Напиши продающий пост в Telegram','Как продвигать товар на Wildberries?'],
    placeholder: 'Опишите задачу по маркетингу или бизнесу…',
    thinkingText: 'Дима генерирует идеи…',
    answerLabel: 'МАРКЕТИНГОВОЕ РЕШЕНИЕ',
    answerFont: '"Montserrat", sans-serif',
    hasPhoto: true,
    greeting: 'Хей! 🚀\n\nЯ Дима — маркетолог и копирайтер экосистемы SWAP, созданной в Набережных Челнах — городе смелых идей и нестандартных решений!\n\nОпиши задачу, пришли фото продукта или брифуй голосом — придумаем что-нибудь яркое и цепляющее!',
    voiceGreeting: '',
  },
  {
    id: 'lena',
    name: 'Переводчик Лена',
    emoji: '🌍',
    role: 'Переводчик-лингвист',
    tagline: 'RU · EN · DE · FR · ES · IT · ZH',
    voice: 'nova',
    cardGradient: 'linear-gradient(135deg,#006064,#00838f,#0097a7)',
    cardGlow: 'rgba(0,131,143,0.4)',
    headerGradient: 'linear-gradient(135deg,#006064 0%,#00838f 100%)',
    headerAccent: '#b2ebf2',
    contentBg: '#f0ffff',
    answerColor: '#003338',
    accentColor: '#006064',
    accentBg: '#e0f7fa',
    inputBorder: '#80deea',
    examples: ['Переведи на английский: "Мне нужна ваша помощь"','Как по-немецки "пожалуйста"?','Переведи этот контракт на русский'],
    placeholder: 'Введите текст для перевода или языковой вопрос…',
    thinkingText: 'Лена переводит…',
    answerLabel: 'ПЕРЕВОД',
    answerFont: '"Montserrat", sans-serif',
    hasPhoto: true,
    greeting: 'Привет! 🌍\n\nЯ Лена — переводчик-лингвист экосистемы SWAP, созданной в Набережных Челнах.\n\nВладею русским, английским, немецким, французским, испанским, итальянским и китайским. Введи текст или пришли фото документа — переведу точно и красиво.',
    voiceGreeting: '',
  },
  {
    id: 'galina',
    name: 'Бухгалтер Галина',
    emoji: '📊',
    role: 'Главный бухгалтер',
    tagline: 'Счета · КП · 2-НДФЛ · 3-НДФЛ · Отчёты · PDF',
    voice: 'shimmer',
    cardGradient: 'linear-gradient(135deg,#1a0535,#2d1b6b,#3d2b8a)',
    cardGlow: 'rgba(45,27,107,0.5)',
    headerGradient: 'linear-gradient(135deg,#1a0535 0%,#2d1b6b 100%)',
    headerAccent: '#ffd700',
    contentBg: '#fefcff',
    answerColor: '#1a0535',
    accentColor: '#5c35cc',
    accentBg: '#f0ebff',
    inputBorder: '#b39ddb',
    examples: [
      'Создай счёт на оплату: ООО "Ромашка" → ООО "Василёк", услуга разработки 50 000 ₽',
      'Составь коммерческое предложение на IT-услуги',
      'Как заполнить 3-НДФЛ при продаже квартиры?',
      'Акт выполненных работ: консалтинг 30 000 ₽',
    ],
    placeholder: 'Опишите задачу или запросите документ…',
    thinkingText: 'Галина считает и составляет…',
    answerLabel: 'ОТВЕТ БУХГАЛТЕРА',
    answerFont: '"Roboto", sans-serif',
    hasPhoto: true,
    greeting: 'Добрый день! 📊\n\nЯ Галина — главный бухгалтер экосистемы SWAP, созданной в Набережных Челнах. 25 лет работаю с российским бухгалтерским и налоговым законодательством.\n\nСоставлю счёт, акт, КП, справку 2-НДФЛ, 3-НДФЛ, платёжное поручение — любой документ скачаешь в PDF. Задавай вопросы или скажи что нужно составить.',
    voiceGreeting: '',
  },
  {
    id: 'vasya',
    name: 'Механик Вася',
    emoji: '🔩',
    role: 'Автомеханик',
    tagline: 'Авто · Мото · Катера · Лодки · Любые марки',
    voice: 'echo',
    cardGradient: 'linear-gradient(135deg,#3a1a00,#7b3300,#a04000)',
    cardGlow: 'rgba(123,51,0,0.45)',
    headerGradient: 'linear-gradient(135deg,#3a1a00 0%,#7b3300 100%)',
    headerAccent: '#ffcc80',
    contentBg: '#fff9f0',
    answerColor: '#2a1000',
    accentColor: '#bf6000',
    accentBg: '#fff3e0',
    inputBorder: '#ffb74d',
    examples: [
      'Горит чек — Ford Focus 2, что это?',
      'Мотор троит на холодную — причины',
      'Скрипят тормоза при торможении — что делать?',
      'Лодочный мотор не заводится после зимы',
    ],
    placeholder: 'Назови марку/модель и опиши проблему…',
    thinkingText: 'Вася смотрит на железо…',
    answerLabel: 'ДИАГНОЗ МЕХАНИКА',
    answerFont: '"Roboto", sans-serif',
    hasPhoto: true,
    greeting: 'Здорово! 🔩\n\nВася — механик. Работаю в экосистеме SWAP, собранной в Набережных Челнах — городе, где родился КАМАЗ и где в технике разбираются с детства.\n\nЛюбые авто, мото, катера и лодки — всё знаю. Лампочка горит, что-то скрипит, не заводится, жрёт масло, тянет в сторону — описывай или скидывай фото. Поставлю диагноз и объясню что делать. Погнали! 🚗🛥️',
    voiceGreeting: '',
  },
  {
    id: 'dyadya_vanya',
    name: 'Дядя Ваня',
    emoji: '🎣',
    role: 'Рыбак-эксперт',
    tagline: 'Клёв · Снасти · Места · Сезоны · Узлы',
    voice: 'echo',
    cardGradient: 'linear-gradient(135deg,#1a3a1a,#2d5a27,#1e6b3a)',
    cardGlow: 'rgba(30,107,58,0.45)',
    headerGradient: 'linear-gradient(135deg,#0d2b0d 0%,#1a4a1a 60%,#0e3d20 100%)',
    headerAccent: '#a8e6a3',
    contentBg: '#f0faf0',
    answerColor: '#0d2b0d',
    accentColor: '#1a5c1a',
    accentBg: '#d4edda',
    inputBorder: '#7dbf7d',
    examples: [
      'Когда лучше ловить карпа на Каме?',
      'Какую приманку выбрать на щуку летом?',
      'Как правильно прикормить карася?',
      'Как вязать узел для поводка?',
    ],
    placeholder: 'Спрашивай про рыбалку — Дядя Ваня всё знает!',
    thinkingText: 'Дядя Ваня смотрит на поплавок…',
    answerLabel: 'СОВЕТ ДЯДИ ВАНИ',
    answerFont: '"Georgia", serif',
    hasPhoto: true,
    greeting: 'Здорово! Я Дядя Ваня. 🎣\n\nРыбак с 40-летним стажем, Набережные Челны. Кама, Волга, Белая — свои реки, знаю каждый омут.\n\nСпрашивай про снасти, наживку, места клёва, время выхода, узлы — всё скажу как есть. Только реальные советы, без выдумок.',
    voiceGreeting: '',
  },
  {
    id: 'sveta',
    name: 'Педагог Света',
    emoji: '🌈',
    role: 'Педагог и детский психолог',
    tagline: 'Воспитание · Развитие · Возрастные кризисы',
    voice: 'nova',
    cardGradient: 'linear-gradient(135deg,#33691e,#558b2f,#689f38)',
    cardGlow: 'rgba(85,139,47,0.4)',
    headerGradient: 'linear-gradient(135deg,#33691e 0%,#558b2f 100%)',
    headerAccent: '#dcedc8',
    contentBg: '#f5fff0',
    answerColor: '#1a2e1a',
    accentColor: '#558b2f',
    accentBg: '#f1f8e9',
    inputBorder: '#aed581',
    examples: ['Ребёнок 3 лет бьётся в истериках','Как объяснить ребёнку развод?','Как мотивировать учиться в школе?'],
    placeholder: 'Опишите ситуацию с вашим ребёнком…',
    thinkingText: 'Света обдумывает совет…',
    answerLabel: 'СОВЕТ ПЕДАГОГА',
    answerFont: '"Montserrat", sans-serif',
    hasPhoto: true,
    greeting: 'Здравствуйте. 🌈\n\nЯ Света — педагог и детский психолог экосистемы SWAP, созданной в Набережных Челнах с любовью к детям и их родителям.\n\nРасскажите о вашем ребёнке — найдём решение вместе, тепло и без осуждений.',
    voiceGreeting: '',
  },
];
