/* ═══════════════════════════════════════════════════════════════════
   SWAIP — словари для генерации мастер-ключей на всех языках
   Каждый язык: 200+ простых существительных, легко запомнить
═══════════════════════════════════════════════════════════════════ */

const RU = [
  'Дуб','Сосна','Ёж','Машина','Река','Луна','Ключ','Ветер','Звезда','Огонь',
  'Берёза','Окно','Лес','Море','Небо','Гора','Камень','Вода','Земля','Солнце',
  'Птица','Рыба','Волк','Медведь','Лиса','Заяц','Кот','Пёс','Конь','Орёл',
  'Цветок','Трава','Лист','Ветка','Корень','Семя','Плод','Яблоко','Груша','Слива',
  'Хлеб','Соль','Мёд','Молоко','Масло','Сыр','Яйцо','Суп','Каша','Пирог',
  'Дом','Дверь','Крыша','Стена','Пол','Стол','Стул','Кровать','Шкаф','Полка',
  'Город','Село','Дорога','Мост','Поле','Сад','Парк','Пруд','Озеро','Болото',
  'Книга','Слово','Буква','Перо','Карта','Рисунок','Нота','Песня','Танец','Игра',
  'Сила','Свет','Тень','Звук','Цвет','Форма','Круг','Линия','Точка','Угол',
  'Друг','Семья','Брат','Сестра','Мать','Отец','Сын','Дочь','Дед','Баба',
  'Труд','Дело','Путь','Шаг','Миг','День','Ночь','Год','Век','Эпоха',
  'Мечта','Надежда','Вера','Любовь','Радость','Печаль','Смех','Слеза','Улыбка','Взгляд',
  'Снег','Дождь','Гром','Молния','Туман','Лёд','Роса','Мороз','Жара','Буря',
  'Серебро','Золото','Медь','Железо','Сталь','Стекло','Камень','Глина','Песок','Дерево',
  'Север','Юг','Восток','Запад','Верх','Низ','Даль','Глубь','Высь','Ширь',
  'Река','Волна','Берег','Якорь','Парус','Корабль','Весло','Рыбак','Охотник','Пахарь',
  'Флаг','Герб','Знак','Печать','Монета','Кольцо','Браслет','Лента','Нить','Узел',
  'Перст','Ладонь','Плечо','Спина','Голос','Взмах','Поклон','Прыжок','Бег','Шаг',
  'Заря','Закат','Рассвет','Полдень','Полночь','Сумрак','Свет','Мрак','Тишь','Гул',
  'Сказка','Миф','Легенда','Клятва','Тайна','Загадка','Ответ','Вопрос','Истина','Ложь',
];

const EN = [
  'Oak','Pine','Moon','Star','Wind','Fire','River','Mountain','Cloud','Stone',
  'Bird','Fish','Wolf','Bear','Fox','Cat','Dog','Horse','Eagle','Swan',
  'Flower','Grass','Leaf','Branch','Root','Seed','Fruit','Apple','Pear','Rose',
  'Bread','Salt','Honey','Milk','Butter','Cheese','Egg','Soup','Cake','Pie',
  'House','Door','Roof','Wall','Floor','Table','Chair','Bed','Shelf','Window',
  'City','Road','Bridge','Field','Garden','Park','Lake','River','Forest','Hill',
  'Book','Word','Letter','Map','Song','Dance','Game','Light','Shadow','Sound',
  'Friend','Family','Brother','Sister','Mother','Father','Son','Daughter','Hand','Heart',
  'Work','Path','Step','Day','Night','Year','Age','Dream','Hope','Love',
  'Snow','Rain','Thunder','Fog','Ice','Frost','Storm','Wave','Shore','Anchor',
  'Silver','Gold','Iron','Steel','Glass','Clay','Sand','Wood','Flame','Smoke',
  'North','South','East','West','Sky','Sea','Land','Air','Sun','Earth',
  'Ring','Chain','Rope','Knot','Blade','Shield','Arrow','Bow','Crown','Key',
  'Smile','Tear','Laugh','Shout','Whisper','Dance','Leap','Run','Fall','Rise',
  'Dawn','Dusk','Noon','Midnight','Shadow','Glow','Spark','Beam','Ray','Mist',
  'Story','Myth','Secret','Answer','Truth','Vow','Seal','Mark','Sign','Flag',
  'Stream','Pool','Spring','Marsh','Cliff','Cave','Valley','Peak','Shore','Isle',
  'Hawk','Raven','Dove','Crane','Deer','Elk','Hare','Lynx','Owl','Bat',
  'Vine','Fern','Moss','Reed','Thorn','Berry','Acorn','Cone','Bud','Bloom',
  'Drum','Flute','Harp','Bell','Lute','Chord','Rhythm','Verse','Tale','Spell',
];

const ZH = [
  '山','水','火','风','云','雨','雪','月','星','日',
  '树','花','草','叶','根','果','林','竹','松','梅',
  '鸟','鱼','龙','虎','马','牛','羊','猫','狗','鹰',
  '家','门','窗','桥','路','城','村','田','园','湖',
  '书','字','歌','画','诗','琴','鼓','笛','灯','镜',
  '心','手','眼','耳','口','脸','发','背','足','臂',
  '金','银','玉','铜','铁','木','石','土','水','冰',
  '梦','爱','光','影','声','色','力','美','善','真',
  '春','夏','秋','冬','晨','夜','朝','暮','时','年',
  '父','母','子','女','兄','妹','友','师','王','民',
  '海','江','河','湖','泉','瀑','洞','峰','谷','原',
  '船','帆','舵','锚','桨','网','钩','剑','盾','弓',
  '米','盐','糖','茶','酒','油','蜜','豆','麦','稻',
  '旗','印','环','链','结','冠','珠','玫','兰','荷',
  '笑','泪','怒','喜','忧','愁','希','忆','念','思',
  '道','路','法','理','天','地','人','心','命','运',
  '云','雾','霜','露','雷','电','虹','晴','阴','风',
  '北','南','东','西','上','下','前','后','左','右',
  '诚','信','义','勇','智','仁','礼','孝','忠','廉',
  '花','鸟','鱼','虫','蝶','莲','菊','桃','柳','桂',
];

const ES = [
  'Roble','Pino','Luna','Estrella','Viento','Fuego','Río','Montaña','Nube','Piedra',
  'Pájaro','Pez','Lobo','Oso','Zorro','Gato','Perro','Caballo','Águila','Cisne',
  'Flor','Hierba','Hoja','Rama','Raíz','Semilla','Fruto','Manzana','Rosa','Palma',
  'Pan','Sal','Miel','Leche','Queso','Huevo','Sopa','Torta','Vino','Aceite',
  'Casa','Puerta','Techo','Pared','Mesa','Silla','Cama','Libro','Mapa','Llave',
  'Ciudad','Camino','Puente','Campo','Jardín','Parque','Lago','Bosque','Colina','Valle',
  'Canción','Danza','Luz','Sombra','Sonido','Color','Fuerza','Sueño','Amor','Paz',
  'Amigo','Familia','Madre','Padre','Hijo','Hija','Mano','Corazón','Voz','Alma',
  'Nieve','Lluvia','Trueno','Niebla','Hielo','Ola','Orilla','Mar','Playa','Isla',
  'Plata','Oro','Hierro','Cristal','Arena','Madera','Llama','Humo','Brillo','Sombra',
  'Norte','Sur','Este','Oeste','Cielo','Tierra','Aire','Sol','Luna','Mar',
  'Anillo','Corona','Flecha','Escudo','Espada','Arco','Cuerda','Nudo','Llave','Sello',
  'Sonrisa','Lágrima','Risa','Susurro','Salto','Camino','Paso','Vuelo','Carrera','Danza',
  'Alba','Ocaso','Mediodía','Medianoche','Bruma','Destello','Rayo','Chispa','Fulgor','Neblina',
  'Cuento','Mito','Secreto','Verdad','Promesa','Signo','Bandera','Marca','Huella','Rastro',
  'Arroyo','Manantial','Acantilado','Cueva','Cumbre','Costa','Pradera','Llanura','Desierto','Selva',
  'Halcón','Cuervo','Paloma','Grulla','Ciervo','Liebre','Lince','Búho','Murciélago','Puma',
  'Vid','Helecho','Musgo','Caña','Espina','Baya','Bellota','Brote','Flor','Racimo',
  'Tambor','Flauta','Arpa','Campana','Acorde','Ritmo','Verso','Cuento','Hechizo','Canto',
  'Roca','Lava','Vapor','Cristal','Coral','Perla','Ámbar','Jade','Rubí','Zafiro',
];

const AR = [
  'جبل','نهر','بحر','شمس','قمر','نجم','ريح','نار','ماء','أرض',
  'شجر','زهر','عشب','ورق','جذر','ثمر','تفاح','وردة','نخل','أرز',
  'طير','سمك','أسد','نمر','ذئب','ثعلب','قط','كلب','حصان','نسر',
  'بيت','باب','سقف','حائط','طاولة','كرسي','سرير','كتاب','خريطة','مفتاح',
  'مدينة','طريق','جسر','حقل','بستان','بحيرة','غابة','تل','واد','سهل',
  'خبز','ملح','عسل','حليب','زيت','جبن','بيضة','حساء','تمر','زيتون',
  'أغنية','رقص','ضوء','ظل','صوت','لون','قوة','حلم','حب','سلام',
  'صديق','أسرة','أم','أب','ابن','بنت','يد','قلب','روح','صوت',
  'ثلج','مطر','رعد','ضباب','جليد','موج','شاطئ','خليج','جزيرة','كهف',
  'فضة','ذهب','حديد','زجاج','رمل','خشب','لهب','دخان','بريق','ظلام',
  'شمال','جنوب','شرق','غرب','سماء','أرض','هواء','بحر','جبل','صحراء',
  'خاتم','تاج','سهم','درع','سيف','قوس','حبل','عقدة','ختم','علم',
  'ابتسامة','دمعة','ضحكة','همسة','قفزة','خطوة','طيران','وثبة','هرولة','رقص',
  'فجر','غروب','ظهر','منتصف ليل','ضباب','وميض','شعاع','شرارة','توهج','ندى',
  'قصة','أسطورة','سر','حقيقة','وعد','علامة','راية','أثر','بصمة','ذكرى',
  'غدير','ينبوع','منحدر','قمة','ساحل','مرج','سهل','صحراء','غابة','أدغال',
  'صقر','غراب','حمامة','غزال','أرنب','بومة','عقاب','حوت','دلفين','طاووس',
  'كرمة','سرخس','طحلب','قصبة','شوكة','توتة','بندق','برعم','زهرة','عنقود',
  'طبل','ناي','قيثارة','جرس','لحن','إيقاع','بيت شعر','حكاية','نشيد','تعويذة',
  'صخرة','مرجان','لؤلؤ','كهرمان','ياقوت','زمرد','بلور','عقيق','فيروز','ذهب',
];

const FR = [
  'Chêne','Pin','Lune','Étoile','Vent','Feu','Rivière','Montagne','Nuage','Pierre',
  'Oiseau','Poisson','Loup','Ours','Renard','Chat','Chien','Cheval','Aigle','Cygne',
  'Fleur','Herbe','Feuille','Branche','Racine','Graine','Fruit','Pomme','Rose','Palme',
  'Pain','Sel','Miel','Lait','Beurre','Fromage','Œuf','Soupe','Gâteau','Tarte',
  'Maison','Porte','Toit','Mur','Table','Chaise','Lit','Livre','Carte','Clé',
  'Ville','Route','Pont','Champ','Jardin','Parc','Lac','Forêt','Colline','Vallée',
  'Chanson','Danse','Lumière','Ombre','Son','Couleur','Force','Rêve','Amour','Paix',
  'Ami','Famille','Mère','Père','Fils','Fille','Main','Cœur','Voix','Âme',
  'Neige','Pluie','Tonnerre','Brouillard','Glace','Vague','Rivage','Mer','Plage','Île',
  'Argent','Or','Fer','Acier','Verre','Sable','Bois','Flamme','Fumée','Éclat',
  'Nord','Sud','Est','Ouest','Ciel','Terre','Air','Soleil','Mer','Plaine',
  'Anneau','Couronne','Flèche','Bouclier','Épée','Arc','Corde','Nœud','Sceau','Drapeau',
  'Sourire','Larme','Rire','Murmure','Saut','Chemin','Pas','Vol','Course','Danse',
  'Aube','Crépuscule','Midi','Minuit','Brume','Éclair','Rayon','Étincelle','Lueur','Brouillard',
  'Conte','Mythe','Secret','Vérité','Serment','Signe','Marque','Trace','Souvenir','Vision',
  'Ruisseau','Source','Falaise','Grotte','Sommet','Côte','Prairie','Plaine','Désert','Jungle',
  'Faucon','Corbeau','Colombe','Grue','Cerf','Lièvre','Lynx','Hibou','Chauve-souris','Puma',
  'Vigne','Fougère','Mousse','Roseau','Épine','Baie','Gland','Bourgeon','Fleur','Grappe',
  'Tambour','Flûte','Harpe','Cloche','Corde','Rythme','Vers','Conte','Charme','Chant',
  'Rocher','Lave','Corail','Perle','Ambre','Jade','Rubis','Saphir','Cristal','Opale',
];

const DE = [
  'Eiche','Kiefer','Mond','Stern','Wind','Feuer','Fluss','Berg','Wolke','Stein',
  'Vogel','Fisch','Wolf','Bär','Fuchs','Katze','Hund','Pferd','Adler','Schwan',
  'Blume','Gras','Blatt','Ast','Wurzel','Samen','Frucht','Apfel','Rose','Palme',
  'Brot','Salz','Honig','Milch','Butter','Käse','Ei','Suppe','Kuchen','Torte',
  'Haus','Tür','Dach','Wand','Tisch','Stuhl','Bett','Buch','Karte','Schlüssel',
  'Stadt','Weg','Brücke','Feld','Garten','Park','See','Wald','Hügel','Tal',
  'Lied','Tanz','Licht','Schatten','Klang','Farbe','Kraft','Traum','Liebe','Frieden',
  'Freund','Familie','Mutter','Vater','Sohn','Tochter','Hand','Herz','Stimme','Seele',
  'Schnee','Regen','Donner','Nebel','Eis','Welle','Ufer','Meer','Strand','Insel',
  'Silber','Gold','Eisen','Stahl','Glas','Sand','Holz','Flamme','Rauch','Glanz',
  'Norden','Süden','Osten','Westen','Himmel','Erde','Luft','Sonne','Meer','Ebene',
  'Ring','Krone','Pfeil','Schild','Schwert','Bogen','Seil','Knoten','Siegel','Fahne',
  'Lächeln','Träne','Lachen','Flüstern','Sprung','Pfad','Schritt','Flug','Lauf','Tanz',
  'Morgen','Abend','Mittag','Mitternacht','Nebel','Blitz','Strahl','Funke','Glut','Tau',
  'Märchen','Sage','Geheimnis','Wahrheit','Schwur','Zeichen','Fahne','Spur','Erinnerung','Traum',
  'Bach','Quelle','Klippe','Höhle','Gipfel','Küste','Wiese','Ebene','Wüste','Urwald',
  'Falke','Rabe','Taube','Kranich','Hirsch','Hase','Luchs','Eule','Fledermaus','Puma',
  'Rebe','Farn','Moos','Schilf','Dorn','Beere','Eichel','Knospe','Blüte','Traube',
  'Trommel','Flöte','Harfe','Glocke','Akkord','Rhythmus','Vers','Sage','Zauber','Lied',
  'Fels','Koralle','Perle','Bernstein','Jade','Rubin','Saphir','Kristall','Opal','Achat',
];

const JA = [
  '山','川','海','空','星','月','日','風','雨','雪',
  '木','花','草','葉','根','実','桜','松','竹','梅',
  '鳥','魚','虎','熊','狐','猫','犬','馬','鷹','鶴',
  '家','扉','橋','道','庭','湖','森','丘','谷','野',
  '書','歌','光','影','音','色','夢','愛','心','魂',
  '父','母','子','友','師','兄','妹','手','目','声',
  '春','夏','秋','冬','朝','夜','昼','夕','時','年',
  '雪','霜','霧','虹','嵐','波','岸','浜','島','洞',
  '金','銀','鉄','木','石','砂','炎','煙','光','闇',
  '北','南','東','西','天','地','空','海','山','原',
  '剣','盾','弓','矢','冠','印','旗','縄','鍵','鐘',
  '笑','涙','歌','踊','跳','走','飛','泳','登','進',
  '暁','夕','正午','夜半','霞','閃','光','火花','輝','露',
  '話','伝','秘','真','誓','印','記','跡','思','夢',
  '滝','泉','崖','峰','浜','草原','平野','砂漠','密林','原野',
  '鷹','鴉','鳩','鶴','鹿','兎','梟','鯨','蝶','龍',
  '桃','柳','蘭','菊','葡萄','松葉','苔','芽','蕾','穂',
  '太鼓','笛','琴','鐘','調','律','詩','物語','術','歌',
  '岩','珊瑚','真珠','琥珀','翡翠','紅玉','青玉','水晶','瑪瑙','白玉',
  '道','理','法','義','仁','礼','智','信','勇','徳',
];

const KO = [
  '산','강','바다','하늘','별','달','해','바람','비','눈',
  '나무','꽃','풀','잎','뿌리','열매','벚꽃','소나무','대나무','매화',
  '새','물고기','호랑이','곰','여우','고양이','개','말','독수리','학',
  '집','문','다리','길','정원','호수','숲','언덕','골짜기','들판',
  '책','노래','빛','그림자','소리','꿈','사랑','마음','영혼','목소리',
  '아버지','어머니','아들','딸','친구','형','누나','손','눈','가슴',
  '봄','여름','가을','겨울','아침','밤','낮','저녁','시간','해',
  '눈','서리','안개','무지개','폭풍','파도','해변','섬','동굴','폭포',
  '금','은','철','나무','돌','모래','불꽃','연기','빛','어둠',
  '북','남','동','서','하늘','땅','공기','바다','산','평야',
  '칼','방패','활','화살','왕관','도장','깃발','밧줄','열쇠','종',
  '웃음','눈물','노래','춤','도약','달리기','비행','수영','등반','전진',
  '새벽','저녁','정오','한밤중','안개','번개','햇살','불꽃','이슬','무지개',
  '이야기','전설','비밀','진실','맹세','표시','깃발','흔적','기억','꿈',
  '폭포','샘','절벽','봉우리','해안','초원','평원','사막','밀림','고원',
  '매','까마귀','비둘기','두루미','사슴','토끼','올빼미','고래','나비','용',
  '복숭아','버드나무','난초','국화','포도','이끼','새싹','꽃봉오리','이삭','열매',
  '북','피리','거문고','종','음률','시','이야기','주문','노래','춤',
  '바위','산호','진주','호박','비취','루비','사파이어','수정','마노','옥',
  '도','이치','법','의','인','예','지','신','용','덕',
];

const TR = [
  'Meşe','Çam','Ay','Yıldız','Rüzgar','Ateş','Nehir','Dağ','Bulut','Taş',
  'Kuş','Balık','Kurt','Ayı','Tilki','Kedi','Köpek','At','Kartal','Kuğu',
  'Çiçek','Ot','Yaprak','Dal','Kök','Tohum','Meyve','Elma','Gül','Hurma',
  'Ekmek','Tuz','Bal','Süt','Yağ','Peynir','Yumurta','Çorba','Pasta','Turta',
  'Ev','Kapı','Çatı','Duvar','Masa','Sandalye','Yatak','Kitap','Harita','Anahtar',
  'Şehir','Yol','Köprü','Tarla','Bahçe','Park','Göl','Orman','Tepe','Vadi',
  'Şarkı','Dans','Işık','Gölge','Ses','Renk','Güç','Hayal','Sevgi','Barış',
  'Dost','Aile','Anne','Baba','Oğul','Kız','El','Kalp','Ses','Ruh',
  'Kar','Yağmur','Gök','Sis','Buz','Dalga','Kıyı','Deniz','Plaj','Ada',
  'Gümüş','Altın','Demir','Çelik','Cam','Kum','Odun','Alev','Duman','Parıltı',
  'Kuzey','Güney','Doğu','Batı','Gökyüzü','Toprak','Hava','Güneş','Deniz','Ova',
  'Yüzük','Taç','Ok','Kalkan','Kılıç','Yay','Halat','Düğüm','Mühür','Bayrak',
  'Gülüş','Gözyaşı','Kahkaha','Fısıltı','Sıçrayış','Yol','Adım','Uçuş','Koşu','Dans',
  'Şafak','Alacakaranlık','Öğle','Gece yarısı','Sis','Şimşek','Işın','Kıvılcım','Parıltı','Çiğ',
  'Masal','Efsane','Sır','Gerçek','Yemin','İşaret','Bayrak','İz','Anı','Hayal',
  'Dere','Kaynak','Uçurum','Mağara','Zirve','Kıyı','Çayır','Ova','Çöl','Orman',
  'Doğan','Karga','Güvercin','Turna','Geyik','Tavşan','Vaşak','Baykuş','Yarasa','Puma',
  'Asma','Eğreltiotu','Yosun','Saz','Diken','Böğürtlen','Palamudu','Tomurcuk','Çiçek','Salkım',
  'Davul','Flüt','Harp','Çan','Akor','Ritim','Dize','Masal','Büyü','Şarkı',
  'Kaya','Mercan','İnci','Kehribar','Yeşim','Yakut','Safir','Kristal','Akik','Firuze',
];

const UK = [
  'Дуб','Сосна','Місяць','Зірка','Вітер','Вогонь','Річка','Гора','Хмара','Камінь',
  'Птах','Риба','Вовк','Ведмідь','Лисиця','Кіт','Пес','Кінь','Орел','Лебідь',
  'Квітка','Трава','Листок','Гілка','Корінь','Насіння','Плід','Яблуко','Груша','Роза',
  'Хліб','Сіль','Мед','Молоко','Масло','Сир','Яйце','Суп','Пиріг','Торт',
  'Дім','Двері','Дах','Стіна','Стіл','Стілець','Ліжко','Книга','Карта','Ключ',
  'Місто','Дорога','Міст','Поле','Сад','Парк','Озеро','Ліс','Пагорб','Долина',
  'Пісня','Танець','Світло','Тінь','Звук','Колір','Сила','Мрія','Любов','Мир',
  'Друг','Родина','Мати','Батько','Син','Дочка','Рука','Серце','Голос','Душа',
  'Сніг','Дощ','Грім','Туман','Лід','Хвиля','Берег','Море','Пляж','Острів',
  'Срібло','Золото','Залізо','Сталь','Скло','Пісок','Дерево','Полум\'я','Дим','Блиск',
  'Північ','Південь','Схід','Захід','Небо','Земля','Повітря','Сонце','Море','Рівнина',
  'Кільце','Корона','Стріла','Щит','Меч','Лук','Мотузка','Вузол','Печать','Прапор',
  'Усмішка','Сльоза','Сміх','Шепіт','Стрибок','Шлях','Крок','Політ','Біг','Танець',
  'Світанок','Сутінки','Полудень','Північ','Туман','Блискавка','Промінь','Іскра','Сяйво','Роса',
  'Казка','Легенда','Таємниця','Правда','Клятва','Знак','Прапор','Слід','Пам\'ять','Мрія',
  'Струмок','Джерело','Скеля','Печера','Вершина','Берег','Луг','Рівнина','Пустеля','Джунглі',
  'Сокіл','Ворон','Голуб','Журавель','Олень','Заєць','Рись','Сова','Кажан','Пума',
  'Виноград','Папороть','Мох','Очерет','Терен','Ягода','Жолудь','Брунька','Квітка','Гроно',
  'Барабан','Флейта','Арфа','Дзвін','Акорд','Ритм','Вірш','Казка','Чари','Пісня',
  'Скеля','Корал','Перлина','Бурштин','Жадеїт','Рубін','Сапфір','Кристал','Агат','Опал',
];

const PT = [
  'Carvalho','Pinheiro','Lua','Estrela','Vento','Fogo','Rio','Montanha','Nuvem','Pedra',
  'Pássaro','Peixe','Lobo','Urso','Raposa','Gato','Cachorro','Cavalo','Águia','Cisne',
  'Flor','Grama','Folha','Galho','Raiz','Semente','Fruto','Maçã','Rosa','Palma',
  'Pão','Sal','Mel','Leite','Manteiga','Queijo','Ovo','Sopa','Bolo','Torta',
  'Casa','Porta','Teto','Parede','Mesa','Cadeira','Cama','Livro','Mapa','Chave',
  'Cidade','Caminho','Ponte','Campo','Jardim','Parque','Lago','Floresta','Colina','Vale',
  'Canção','Dança','Luz','Sombra','Som','Cor','Força','Sonho','Amor','Paz',
  'Amigo','Família','Mãe','Pai','Filho','Filha','Mão','Coração','Voz','Alma',
  'Neve','Chuva','Trovão','Névoa','Gelo','Onda','Orla','Mar','Praia','Ilha',
  'Prata','Ouro','Ferro','Aço','Vidro','Areia','Madeira','Chama','Fumaça','Brilho',
  'Norte','Sul','Leste','Oeste','Céu','Terra','Ar','Sol','Mar','Planície',
  'Anel','Coroa','Flecha','Escudo','Espada','Arco','Corda','Nó','Selo','Bandeira',
  'Sorriso','Lágrima','Riso','Sussurro','Salto','Caminho','Passo','Voo','Corrida','Dança',
  'Alvorecer','Crepúsculo','Meio-dia','Meia-noite','Névoa','Relâmpago','Raio','Faísca','Fulgor','Orvalho',
  'Conto','Mito','Segredo','Verdade','Jura','Sinal','Bandeira','Rastro','Memória','Visão',
  'Riacho','Nascente','Penhasco','Caverna','Cume','Costa','Pradaria','Planície','Deserto','Selva',
  'Falcão','Corvo','Pombo','Grou','Veado','Lebre','Lince','Coruja','Morcego','Puma',
  'Videira','Samambaia','Musgo','Junco','Espinho','Baga','Bolota','Broto','Flor','Cacho',
  'Tambor','Flauta','Harpa','Sino','Acorde','Ritmo','Verso','Conto','Encanto','Canto',
  'Rocha','Coral','Pérola','Âmbar','Jade','Rubi','Safira','Cristal','Ágata','Opala',
];

const IT = [
  'Quercia','Pino','Luna','Stella','Vento','Fuoco','Fiume','Montagna','Nuvola','Pietra',
  'Uccello','Pesce','Lupo','Orso','Volpe','Gatto','Cane','Cavallo','Aquila','Cigno',
  'Fiore','Erba','Foglia','Ramo','Radice','Seme','Frutto','Mela','Rosa','Palma',
  'Pane','Sale','Miele','Latte','Burro','Formaggio','Uovo','Zuppa','Torta','Tarta',
  'Casa','Porta','Tetto','Muro','Tavolo','Sedia','Letto','Libro','Mappa','Chiave',
  'Città','Strada','Ponte','Campo','Giardino','Parco','Lago','Bosco','Collina','Valle',
  'Canzone','Danza','Luce','Ombra','Suono','Colore','Forza','Sogno','Amore','Pace',
  'Amico','Famiglia','Madre','Padre','Figlio','Figlia','Mano','Cuore','Voce','Anima',
  'Neve','Pioggia','Tuono','Nebbia','Ghiaccio','Onda','Riva','Mare','Spiaggia','Isola',
  'Argento','Oro','Ferro','Acciaio','Vetro','Sabbia','Legno','Fiamma','Fumo','Splendore',
  'Nord','Sud','Est','Ovest','Cielo','Terra','Aria','Sole','Mare','Pianura',
  'Anello','Corona','Freccia','Scudo','Spada','Arco','Corda','Nodo','Sigillo','Bandiera',
  'Sorriso','Lacrima','Risata','Sussurro','Salto','Sentiero','Passo','Volo','Corsa','Danza',
  'Alba','Crepuscolo','Mezzogiorno','Mezzanotte','Nebbia','Fulmine','Raggio','Scintilla','Bagliore','Rugiada',
  'Favola','Mito','Segreto','Verità','Giuramento','Segno','Bandiera','Traccia','Memoria','Visione',
  'Ruscello','Sorgente','Scogliera','Grotta','Cima','Costa','Prato','Pianura','Deserto','Giungla',
  'Falco','Corvo','Colomba','Gru','Cervo','Lepre','Lince','Gufo','Pipistrello','Puma',
  'Vigna','Felce','Muschio','Canna','Spina','Bacca','Ghianda','Germoglio','Fiore','Grappolo',
  'Tamburo','Flauto','Arpa','Campana','Accordo','Ritmo','Verso','Favola','Incanto','Canto',
  'Roccia','Corallo','Perla','Ambra','Giada','Rubino','Zaffiro','Cristallo','Agata','Opale',
];

const PL = [
  'Dąb','Sosna','Księżyc','Gwiazda','Wiatr','Ogień','Rzeka','Góra','Chmura','Kamień',
  'Ptak','Ryba','Wilk','Niedźwiedź','Lis','Kot','Pies','Koń','Orzeł','Łabędź',
  'Kwiat','Trawa','Liść','Gałąź','Korzeń','Nasienie','Owoc','Jabłko','Gruszka','Róża',
  'Chleb','Sól','Miód','Mleko','Masło','Ser','Jajko','Zupa','Ciasto','Tort',
  'Dom','Drzwi','Dach','Ściana','Stół','Krzesło','Łóżko','Książka','Mapa','Klucz',
  'Miasto','Droga','Most','Pole','Ogród','Park','Jezioro','Las','Wzgórze','Dolina',
  'Pieśń','Taniec','Światło','Cień','Dźwięk','Kolor','Siła','Marzenie','Miłość','Pokój',
  'Przyjaciel','Rodzina','Matka','Ojciec','Syn','Córka','Ręka','Serce','Głos','Dusza',
  'Śnieg','Deszcz','Grzmot','Mgła','Lód','Fala','Brzeg','Morze','Plaża','Wyspa',
  'Srebro','Złoto','Żelazo','Stal','Szkło','Piasek','Drewno','Płomień','Dym','Blask',
  'Północ','Południe','Wschód','Zachód','Niebo','Ziemia','Powietrze','Słońce','Morze','Równina',
  'Pierścień','Korona','Strzała','Tarcza','Miecz','Łuk','Lina','Węzeł','Pieczęć','Flaga',
  'Uśmiech','Łza','Śmiech','Szept','Skok','Ścieżka','Krok','Lot','Bieg','Taniec',
  'Świt','Zmierzch','Południe','Północ','Mgła','Błyskawica','Promień','Iskra','Blask','Rosa',
  'Bajka','Mit','Tajemnica','Prawda','Przysięga','Znak','Flaga','Ślad','Pamięć','Wizja',
  'Strumień','Źródło','Klif','Jaskinia','Szczyt','Wybrzeże','Łąka','Równina','Pustynia','Dżungla',
  'Sokół','Kruk','Gołąb','Żuraw','Jeleń','Zając','Ryś','Sowa','Nietoperz','Puma',
  'Winorośl','Paproć','Mech','Trzcina','Cierń','Jagoda','Żołądź','Pąk','Kwiat','Kiść',
  'Bęben','Flet','Harfa','Dzwon','Akord','Rytm','Wers','Bajka','Czar','Pieśń',
  'Skała','Koral','Perła','Bursztyn','Jadeit','Rubin','Szafir','Kryształ','Agat','Opal',
];

const HI = [
  'बरगद','पाइन','चाँद','तारा','हवा','आग','नदी','पहाड़','बादल','पत्थर',
  'पक्षी','मछली','भेड़िया','भालू','लोमड़ी','बिल्ली','कुत्ता','घोड़ा','बाज','हंस',
  'फूल','घास','पत्ता','शाखा','जड़','बीज','फल','सेब','गुलाब','कमल',
  'रोटी','नमक','शहद','दूध','मक्खन','पनीर','अंडा','सूप','केक','पाई',
  'घर','दरवाजा','छत','दीवार','मेज','कुर्सी','बिस्तर','किताब','नक्शा','चाबी',
  'शहर','रास्ता','पुल','खेत','बगीचा','पार्क','झील','जंगल','पहाड़ी','घाटी',
  'गाना','नृत्य','रोशनी','छाया','आवाज','रंग','शक्ति','सपना','प्यार','शांति',
  'दोस्त','परिवार','माँ','पिता','बेटा','बेटी','हाथ','दिल','आवाज','आत्मा',
  'बर्फ','बारिश','गर्जन','कोहरा','बर्फ','लहर','किनारा','समुद्र','समुद्रतट','द्वीप',
  'चांदी','सोना','लोहा','इस्पात','कांच','रेत','लकड़ी','लपट','धुआं','चमक',
  'उत्तर','दक्षिण','पूर्व','पश्चिम','आकाश','धरती','हवा','सूरज','समुद्र','मैदान',
  'अंगूठी','मुकुट','तीर','ढाल','तलवार','धनुष','रस्सी','गांठ','मुहर','झंडा',
  'मुस्कान','आँसू','हँसी','फुसफुसाहट','छलाँग','रास्ता','कदम','उड़ान','दौड़','नृत्य',
  'भोर','शाम','दोपहर','आधी रात','कोहरा','बिजली','किरण','चिंगारी','चमक','ओस',
  'कहानी','मिथक','रहस्य','सच','वादा','चिह्न','झंडा','निशान','यादें','दृष्टि',
  'नाला','झरना','चट्टान','गुफा','चोटी','तट','घास का मैदान','मैदान','रेगिस्तान','जंगल',
  'बाज','कौआ','कबूतर','सारस','हिरण','खरगोश','लिंक्स','उल्लू','चमगादड़','तेंदुआ',
  'अंगूर','फर्न','काई','नरकट','कांटा','बेरी','बलूत','कली','फूल','गुच्छा',
  'ढोल','बाँसुरी','वीणा','घंटी','राग','लय','पंक्ति','कहानी','मंत्र','गीत',
  'चट्टान','मूंगा','मोती','एम्बर','जेड','माणिक','नीलम','क्रिस्टल','मणि','ओपल',
];

/* Для всех остальных языков — английский список */
export const WORD_LISTS: Record<string, string[]> = {
  ru: RU,
  be: RU,   /* Belarusian */
  uk: UK,
  en: EN,
  zh: ZH,
  zh_TW: ZH,
  es: ES,
  ar: AR,
  fr: FR,
  de: DE,
  ja: JA,
  ko: KO,
  tr: TR,
  pt: PT,
  pt_BR: PT,
  it: IT,
  pl: PL,
  hi: HI,
  /* Fallback на английский */
  af: EN, az: EN, bg: EN, bn: EN, ca: EN, cs: EN, da: EN, el: EN, et: EN,
  eu: EN, fa: EN, fi: EN, gl: EN, gu: EN, he: EN, hr: EN, hu: EN, hy: EN,
  id: EN, is: EN, ka: EN, kk: EN, km: EN, kn: EN, lt: EN, lv: EN, mk: EN,
  ml: EN, mn: EN, mr: EN, ms: EN, my: EN, nb: EN, nl: EN, pa: EN, ro: EN,
  si: EN, sk: EN, sl: EN, sq: EN, sr: EN, sv: EN, sw: EN, ta: EN, te: EN,
  th: EN, ur: EN, uz: EN, vi: EN,
};

export function getWordList(langCode: string): string[] {
  return WORD_LISTS[langCode] || EN;
}
