import { Router, type IRouter } from "express";
import healthRouter from "./health";
import accountsRouter from "./accounts";
import broadcastsRouter from "./broadcasts";
import messagingRouter from "./messaging";
import sessionsRouter from "./sessions";
import interactionsRouter from "./interactions";
import moderationRouter from "./moderation";
import audioUploadRouter from "./audioUpload";
import imageUploadRouter from "./imageUpload";
import greetingUploadRouter from "./greetingUpload";
import videoUploadRouter from "./videoUpload";
import documentUploadRouter from "./documentUpload";
import chunkUploadRouter from "./chunkUpload";
import storageRouter from "./storage";
import reviewsRouter from "./reviews";
import meetingsRouter from "./meetings";
import storiesRouter from "./stories";
import referralRouter from "./referral";
import pushRouter from "./push";
import exchangeRouter from "./exchange.js";

import ttsRouter from "./tts.js";
import translateRouter from "./translate.js";
import browserProxyRouter from "./browserProxy.js";
import battleRouter from "./battle.js";
import gamesRouter from "./games.js";
import linkPreviewRouter from "./linkPreview";
import botsRouter from "./bots.js";
import miniAppsRouter from "./miniApps.js";
import channelInvitesRouter from "./channelInvites.js";
import loungeRouter from "./lounge.js";
import cinemaRouter from "./cinema.js";
import eventsRouter from "./events.js";
import marketplaceRouter from "./marketplace.js";
import dailyChallengeRouter from "./dailyChallenge.js";
import karaokeRouter from "./karaoke.js";
import pollsRouter from "./polls.js";
import moodsRouter from "./moods.js";
import capsulesRouter from "./capsules.js";
import scheduledMessagesRouter from "./scheduledMessages.js";
import gitPushRouter from "./gitPush.js";
import menuConfigRouter from "./menuConfig.js";
import petyaRouter from "./petya.js";
import assistantsRouter from "./assistants.js";
import gamePlayerRouter from "./gamePlayer.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(sessionsRouter);
router.use(accountsRouter);
router.use(reviewsRouter);
router.use(meetingsRouter);
router.use(broadcastsRouter);
router.use(messagingRouter);
router.use(interactionsRouter);
router.use(moderationRouter);
router.use(audioUploadRouter);
router.use(imageUploadRouter);
router.use(greetingUploadRouter);
router.use(videoUploadRouter);
router.use(documentUploadRouter);
router.use(chunkUploadRouter);
router.use(storageRouter);
router.use(storiesRouter);
router.use("/referral", referralRouter);
router.use(pushRouter);
router.use(exchangeRouter);

router.use(ttsRouter);
router.use(translateRouter);
router.use(browserProxyRouter);
router.use(battleRouter);
router.use(gamesRouter);
router.use(linkPreviewRouter);
router.use(botsRouter);
router.use(miniAppsRouter);
router.use(channelInvitesRouter);
router.use(loungeRouter);
router.use(cinemaRouter);
router.use(eventsRouter);
router.use(marketplaceRouter);
router.use(dailyChallengeRouter);
router.use("/karaoke", karaokeRouter);
router.use(pollsRouter);
router.use(moodsRouter);
router.use(capsulesRouter);
router.use(scheduledMessagesRouter);
router.use(gitPushRouter);
router.use(menuConfigRouter);
router.use(petyaRouter);
router.use(assistantsRouter);
router.use(gamePlayerRouter);

export default router;
