import { Router, type IRouter } from "express";
import healthRouter from "./health";
import accountsRouter from "./accounts";
import broadcastsRouter from "./broadcasts";
import messagingRouter from "./messaging";
import sessionsRouter from "./sessions";
import interactionsRouter from "./interactions";
import moderationRouter from "./moderation";
import audioUploadRouter from "./audioUpload";
import imageUploadRouter from "./imageUpload";
import greetingUploadRouter from "./greetingUpload";
import videoUploadRouter from "./videoUpload";
import documentUploadRouter from "./documentUpload";
import chunkUploadRouter from "./chunkUpload";
import storageRouter from "./storage";
import reviewsRouter from "./reviews";
import meetingsRouter from "./meetings";
import storiesRouter from "./stories";
import referralRouter from "./referral";
import pushRouter from "./push";
import exchangeRouter from "./exchange.js";
import gitPushRouter from "./gitPush.js";
import ttsRouter from "./tts.js";
import browserProxyRouter from "./browserProxy.js";
import battleRouter from "./battle.js";
import gamesRouter from "./games.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(sessionsRouter);
router.use(accountsRouter);
router.use(reviewsRouter);
router.use(meetingsRouter);
router.use(broadcastsRouter);
router.use(messagingRouter);
router.use(interactionsRouter);
router.use(moderationRouter);
router.use(audioUploadRouter);
router.use(imageUploadRouter);
router.use(greetingUploadRouter);
router.use(videoUploadRouter);
router.use(documentUploadRouter);
router.use(chunkUploadRouter);
router.use(storageRouter);
router.use(storiesRouter);
router.use("/referral", referralRouter);
router.use(pushRouter);
router.use(exchangeRouter);
router.use(gitPushRouter);
router.use(ttsRouter);
router.use(browserProxyRouter);
router.use(battleRouter);
router.use(gamesRouter);

export default router;
