// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/swap-brand/Aurora.tsx": () => import("../components/mockups/swap-brand/Aurora.tsx"),
  "./components/mockups/swap-brand/Chrome.tsx": () => import("../components/mockups/swap-brand/Chrome.tsx"),
  "./components/mockups/swap-brand/Fire.tsx": () => import("../components/mockups/swap-brand/Fire.tsx"),
  "./components/mockups/swap-brand/Gold.tsx": () => import("../components/mockups/swap-brand/Gold.tsx"),
  "./components/mockups/swap-brand/Holo.tsx": () => import("../components/mockups/swap-brand/Holo.tsx"),
  "./components/mockups/swap-brand/Ice.tsx": () => import("../components/mockups/swap-brand/Ice.tsx"),
  "./components/mockups/swap-brand/Matrix.tsx": () => import("../components/mockups/swap-brand/Matrix.tsx"),
  "./components/mockups/swap-brand/Minimal.tsx": () => import("../components/mockups/swap-brand/Minimal.tsx"),
  "./components/mockups/swap-brand/Neon.tsx": () => import("../components/mockups/swap-brand/Neon.tsx"),
  "./components/mockups/swap-brand/Plasma.tsx": () => import("../components/mockups/swap-brand/Plasma.tsx")
};
